//
//  DeviceAlert.swift
//  HealthSoftware
//
//  Generated from FHIR 6.0.0-ballot4 (http://hl7.org/fhir/StructureDefinition/DeviceAlert)
//  Copyright 2026 Apple Inc.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

import FMCore

/**
 Documentation of an alert (a.k.a. alarm) generated by a device indicating a noteworthy condition.
 
 Describes a noteworthy condition or occurrence determined to exist by a device.
 */
public struct DeviceAlert: DomainResource {
	
	public static let resourceType: ResourceType = .deviceAlert
	
	/// All possible types for "occurrence[x]"
	public enum OccurrenceX: Equatable, Hashable, Sendable {
		case dateTime(FHIRPrimitive<DateTime>)
		indirect case period(Period)
	}
	
	/// Whether the alert condition has been acknowledged
	public var acknowledged: FHIRPrimitive<FHIRBool>?
	
	/// Who acknowledged the alert condition
	public var acknowledgedBy: Reference?
	
	/// High level categorization of device alert
	public var category: [CodeableConcept]?
	
	/// The meaning of the alert
	public var code: CodeableConcept
	
	/// Contained, inline Resources
	public var contained: [ResourceProxy]?
	
	/// The value causing the alert condition
	public var derivedFrom: [DeviceAlertDerivedFrom]?
	
	/// The Device (or DeviceMetric) that detected the alert condition
	public var device: Reference?
	
	/// Encounter during which the alert condition occurred
	public var encounter: Reference?
	
	/// Additional content defined by implementations
	public var `extension`: [Extension]?
	
	/// Logical id of this artifact
	public var id: FHIRPrimitive<FHIRString>?
	
	/// Business identifier for this device alert
	public var identifier: [Identifier]?
	
	/// A set of rules under which this content was created
	public var implicitRules: FHIRPrimitive<FHIRURI>?
	
	/// Text to be displayed for the alert condition
	public var label: FHIRPrimitive<FHIRString>?
	
	/// Language of the resource content
	public var language: FHIRPrimitive<FHIRString>?
	
	/// Location of the subject when the alert was raised
	public var location: Reference?
	
	/// Metadata about the resource
	public var meta: Meta?
	
	/// Extensions that cannot be ignored
	public var modifierExtension: [Extension]?
	
	/// When the alert condition occurred/is occurring
	/// One of `occurrence[x]`
	public var occurrence: OccurrenceX?
	
	/// Whether the alert condition is currently active
	public var presence: FHIRPrimitive<FHIRBool>
	
	/// high | medium | low | info
	public var priority: CodeableConcept?
	
	/// Procedure during which the alert occurred
	public var procedure: [Reference]?
	
	/// Annunciation or notification of the alert condition
	public var signal: [DeviceAlertSignal]?
	
	/// The current state of the device alert.
	public var status: FHIRPrimitive<DeviceAlertStatus>
	
	/// Who or what the alert is about
	public var subject: Reference
	
	/// Text summary of the resource, for human interpretation
	public var text: Narrative?
	
	/// physiological | technical
	public var type: CodeableConcept?
	
	/// Designated initializer
	public init(
		acknowledged: FHIRPrimitive<FHIRBool>? = nil,
		acknowledgedBy: Reference? = nil,
		category: [CodeableConcept]? = nil,
		code: CodeableConcept,
		contained: [ResourceProxy]? = nil,
		derivedFrom: [DeviceAlertDerivedFrom]? = nil,
		device: Reference? = nil,
		encounter: Reference? = nil,
		`extension`: [Extension]? = nil,
		id: FHIRPrimitive<FHIRString>? = nil,
		identifier: [Identifier]? = nil,
		implicitRules: FHIRPrimitive<FHIRURI>? = nil,
		label: FHIRPrimitive<FHIRString>? = nil,
		language: FHIRPrimitive<FHIRString>? = nil,
		location: Reference? = nil,
		meta: Meta? = nil,
		modifierExtension: [Extension]? = nil,
		occurrence: OccurrenceX? = nil,
		presence: FHIRPrimitive<FHIRBool>,
		priority: CodeableConcept? = nil,
		procedure: [Reference]? = nil,
		signal: [DeviceAlertSignal]? = nil,
		status: FHIRPrimitive<DeviceAlertStatus>,
		subject: Reference,
		text: Narrative? = nil,
		type: CodeableConcept? = nil
	) {
		self.acknowledged = acknowledged
		self.acknowledgedBy = acknowledgedBy
		self.category = category
		self.code = code
		self.contained = contained
		self.derivedFrom = derivedFrom
		self.device = device
		self.encounter = encounter
		self.`extension` = `extension`
		self.id = id
		self.identifier = identifier
		self.implicitRules = implicitRules
		self.label = label
		self.language = language
		self.location = location
		self.meta = meta
		self.modifierExtension = modifierExtension
		self.occurrence = occurrence
		self.presence = presence
		self.priority = priority
		self.procedure = procedure
		self.signal = signal
		self.status = status
		self.subject = subject
		self.text = text
		self.type = type
	}
	
	// MARK: - Codable
	
	private enum CodingKeys: String, CodingKey {
		case resourceType
		case acknowledged; case _acknowledged
		case acknowledgedBy
		case category
		case code
		case contained
		case derivedFrom
		case device
		case encounter
		case `extension` = "extension"
		case id; case _id
		case identifier
		case implicitRules; case _implicitRules
		case label; case _label
		case language; case _language
		case location
		case meta
		case modifierExtension
		case occurrenceDateTime; case _occurrenceDateTime
		case occurrencePeriod
		case presence; case _presence
		case priority
		case procedure
		case signal
		case status; case _status
		case subject
		case text
		case type
	}

	/// Initializer for Decodable
	public init(from decoder: Decoder) throws {
		try decoder.enforceFHIRModelsDepthLimit()
		
		let _container = try decoder.container(keyedBy: CodingKeys.self)
		
		// Decode all our properties (own and inherited)
		self.acknowledged = try FHIRPrimitive<FHIRBool>(from: _container, forKeyIfPresent: .acknowledged, auxiliaryKey: ._acknowledged)
		self.acknowledgedBy = try Reference(from: _container, forKeyIfPresent: .acknowledgedBy)
		self.category = try [CodeableConcept](from: _container, forKeyIfPresent: .category)
		self.code = try CodeableConcept(from: _container, forKey: .code)
		self.contained = try [ResourceProxy](from: _container, forKeyIfPresent: .contained)
		self.derivedFrom = try [DeviceAlertDerivedFrom](from: _container, forKeyIfPresent: .derivedFrom)
		self.device = try Reference(from: _container, forKeyIfPresent: .device)
		self.encounter = try Reference(from: _container, forKeyIfPresent: .encounter)
		self.`extension` = try [Extension](from: _container, forKeyIfPresent: .`extension`)
		self.id = try FHIRPrimitive<FHIRString>(from: _container, forKeyIfPresent: .id, auxiliaryKey: ._id)
		self.identifier = try [Identifier](from: _container, forKeyIfPresent: .identifier)
		self.implicitRules = try FHIRPrimitive<FHIRURI>(from: _container, forKeyIfPresent: .implicitRules, auxiliaryKey: ._implicitRules)
		self.label = try FHIRPrimitive<FHIRString>(from: _container, forKeyIfPresent: .label, auxiliaryKey: ._label)
		self.language = try FHIRPrimitive<FHIRString>(from: _container, forKeyIfPresent: .language, auxiliaryKey: ._language)
		self.location = try Reference(from: _container, forKeyIfPresent: .location)
		self.meta = try Meta(from: _container, forKeyIfPresent: .meta)
		self.modifierExtension = try [Extension](from: _container, forKeyIfPresent: .modifierExtension)
		self.occurrence = try Self._decodeOccurrence(from: _container)
		self.presence = try FHIRPrimitive<FHIRBool>(from: _container, forKey: .presence, auxiliaryKey: ._presence)
		self.priority = try CodeableConcept(from: _container, forKeyIfPresent: .priority)
		self.procedure = try [Reference](from: _container, forKeyIfPresent: .procedure)
		self.signal = try [DeviceAlertSignal](from: _container, forKeyIfPresent: .signal)
		self.status = try FHIRPrimitive<DeviceAlertStatus>(from: _container, forKey: .status, auxiliaryKey: ._status)
		self.subject = try Reference(from: _container, forKey: .subject)
		self.text = try Narrative(from: _container, forKeyIfPresent: .text)
		self.type = try CodeableConcept(from: _container, forKeyIfPresent: .type)
	}
	
	/// Encodable
	public func encode(to encoder: Encoder) throws {
		var _container = encoder.container(keyedBy: CodingKeys.self)
		
		// Encode resourceType
		try _container.encode(Self.resourceType, forKey: .resourceType)
		
		// Encode all our properties (own and inherited)
		try acknowledged?.encode(on: &_container, forKey: .acknowledged, auxiliaryKey: ._acknowledged)
		try acknowledgedBy?.encode(on: &_container, forKey: .acknowledgedBy)
		try category?.encode(on: &_container, forKey: .category)
		try code.encode(on: &_container, forKey: .code)
		try contained?.encode(on: &_container, forKey: .contained)
		try derivedFrom?.encode(on: &_container, forKey: .derivedFrom)
		try device?.encode(on: &_container, forKey: .device)
		try encounter?.encode(on: &_container, forKey: .encounter)
		try `extension`?.encode(on: &_container, forKey: .`extension`)
		try id?.encode(on: &_container, forKey: .id, auxiliaryKey: ._id)
		try identifier?.encode(on: &_container, forKey: .identifier)
		try implicitRules?.encode(on: &_container, forKey: .implicitRules, auxiliaryKey: ._implicitRules)
		try label?.encode(on: &_container, forKey: .label, auxiliaryKey: ._label)
		try language?.encode(on: &_container, forKey: .language, auxiliaryKey: ._language)
		try location?.encode(on: &_container, forKey: .location)
		try meta?.encode(on: &_container, forKey: .meta)
		try modifierExtension?.encode(on: &_container, forKey: .modifierExtension)
		if let _enum = occurrence {
		switch _enum {
		case .dateTime(let _value):
			try _value.encode(on: &_container, forKey: .occurrenceDateTime, auxiliaryKey: ._occurrenceDateTime)
		case .period(let _value):
			try _value.encode(on: &_container, forKey: .occurrencePeriod)
		}
		}
		try presence.encode(on: &_container, forKey: .presence, auxiliaryKey: ._presence)
		try priority?.encode(on: &_container, forKey: .priority)
		try procedure?.encode(on: &_container, forKey: .procedure)
		try signal?.encode(on: &_container, forKey: .signal)
		try status.encode(on: &_container, forKey: .status, auxiliaryKey: ._status)
		try subject.encode(on: &_container, forKey: .subject)
		try text?.encode(on: &_container, forKey: .text)
		try type?.encode(on: &_container, forKey: .type)
	}
	
	// MARK: ValueX Decoders
	
	private static func _decodeOccurrence(
		from _container: KeyedDecodingContainer<CodingKeys>
	) throws -> OccurrenceX? {
		var _t_occurrence: OccurrenceX? = nil
		if let occurrenceDateTime = try FHIRPrimitive<DateTime>(from: _container, forKeyIfPresent: .occurrenceDateTime, auxiliaryKey: ._occurrenceDateTime) {
			_t_occurrence = .dateTime(occurrenceDateTime)
		}
		if let occurrencePeriod = try Period(from: _container, forKeyIfPresent: .occurrencePeriod) {
			if _t_occurrence != nil {
				throw DecodingError.dataCorruptedError(forKey: .occurrencePeriod, in: _container, debugDescription: "More than one value provided for \"occurrence\"")
			}
			_t_occurrence = .period(occurrencePeriod)
		}
		return _t_occurrence
	}
}

/**
 The value causing the alert condition.
 */
public struct DeviceAlertDerivedFrom: BackboneElement {
	
	/// The Observation.component having a value causing the alert condition
	public var component: Coding?
	
	/// Additional content defined by implementations
	public var `extension`: [Extension]?
	
	/// Unique id for inter-element referencing
	public var id: FHIRPrimitive<FHIRString>?
	
	/// The boundaries beyond which a value was detected to cause the alert condition
	public var limit: Range?
	
	/// Extensions that cannot be ignored even if unrecognized
	public var modifierExtension: [Extension]?
	
	/// The Observation having a value causing the alert condition
	public var observation: Reference
	
	/// Designated initializer
	public init(
		component: Coding? = nil,
		`extension`: [Extension]? = nil,
		id: FHIRPrimitive<FHIRString>? = nil,
		limit: Range? = nil,
		modifierExtension: [Extension]? = nil,
		observation: Reference
	) {
		self.component = component
		self.`extension` = `extension`
		self.id = id
		self.limit = limit
		self.modifierExtension = modifierExtension
		self.observation = observation
	}
	
	// MARK: - Codable
	
	private enum CodingKeys: String, CodingKey {
		case component
		case `extension` = "extension"
		case id; case _id
		case limit
		case modifierExtension
		case observation
	}

	/// Initializer for Decodable
	public init(from decoder: Decoder) throws {
		try decoder.enforceFHIRModelsDepthLimit()
		
		let _container = try decoder.container(keyedBy: CodingKeys.self)
		
		// Decode all our properties (own and inherited)
		self.component = try Coding(from: _container, forKeyIfPresent: .component)
		self.`extension` = try [Extension](from: _container, forKeyIfPresent: .`extension`)
		self.id = try FHIRPrimitive<FHIRString>(from: _container, forKeyIfPresent: .id, auxiliaryKey: ._id)
		self.limit = try Range(from: _container, forKeyIfPresent: .limit)
		self.modifierExtension = try [Extension](from: _container, forKeyIfPresent: .modifierExtension)
		self.observation = try Reference(from: _container, forKey: .observation)
	}
	
	/// Encodable
	public func encode(to encoder: Encoder) throws {
		var _container = encoder.container(keyedBy: CodingKeys.self)
		
		// Encode all our properties (own and inherited)
		try component?.encode(on: &_container, forKey: .component)
		try `extension`?.encode(on: &_container, forKey: .`extension`)
		try id?.encode(on: &_container, forKey: .id, auxiliaryKey: ._id)
		try limit?.encode(on: &_container, forKey: .limit)
		try modifierExtension?.encode(on: &_container, forKey: .modifierExtension)
		try observation.encode(on: &_container, forKey: .observation)
	}
}

/**
 Annunciation or notification of the alert condition.
 */
public struct DeviceAlertSignal: BackboneElement {
	
	/// on | off | paused
	public var activationState: CodeableConcept
	
	/// Where the signal is being annunciated
	public var annunciator: CodeableReference?
	
	/// Additional content defined by implementations
	public var `extension`: [Extension]?
	
	/// Unique id for inter-element referencing
	public var id: FHIRPrimitive<FHIRString>?
	
	/// When the signal was being annunciated
	public var indication: Period?
	
	/// How the signal is being annunciated
	public var manifestation: CodeableConcept?
	
	/// Extensions that cannot be ignored even if unrecognized
	public var modifierExtension: [Extension]?
	
	/// on | latched | off | ack
	public var presence: CodeableConcept?
	
	/// Characteristics of the signal manifestation
	public var type: [CodeableConcept]?
	
	/// Designated initializer
	public init(
		activationState: CodeableConcept,
		annunciator: CodeableReference? = nil,
		`extension`: [Extension]? = nil,
		id: FHIRPrimitive<FHIRString>? = nil,
		indication: Period? = nil,
		manifestation: CodeableConcept? = nil,
		modifierExtension: [Extension]? = nil,
		presence: CodeableConcept? = nil,
		type: [CodeableConcept]? = nil
	) {
		self.activationState = activationState
		self.annunciator = annunciator
		self.`extension` = `extension`
		self.id = id
		self.indication = indication
		self.manifestation = manifestation
		self.modifierExtension = modifierExtension
		self.presence = presence
		self.type = type
	}
	
	// MARK: - Codable
	
	private enum CodingKeys: String, CodingKey {
		case activationState
		case annunciator
		case `extension` = "extension"
		case id; case _id
		case indication
		case manifestation
		case modifierExtension
		case presence
		case type
	}

	/// Initializer for Decodable
	public init(from decoder: Decoder) throws {
		try decoder.enforceFHIRModelsDepthLimit()
		
		let _container = try decoder.container(keyedBy: CodingKeys.self)
		
		// Decode all our properties (own and inherited)
		self.activationState = try CodeableConcept(from: _container, forKey: .activationState)
		self.annunciator = try CodeableReference(from: _container, forKeyIfPresent: .annunciator)
		self.`extension` = try [Extension](from: _container, forKeyIfPresent: .`extension`)
		self.id = try FHIRPrimitive<FHIRString>(from: _container, forKeyIfPresent: .id, auxiliaryKey: ._id)
		self.indication = try Period(from: _container, forKeyIfPresent: .indication)
		self.manifestation = try CodeableConcept(from: _container, forKeyIfPresent: .manifestation)
		self.modifierExtension = try [Extension](from: _container, forKeyIfPresent: .modifierExtension)
		self.presence = try CodeableConcept(from: _container, forKeyIfPresent: .presence)
		self.type = try [CodeableConcept](from: _container, forKeyIfPresent: .type)
	}
	
	/// Encodable
	public func encode(to encoder: Encoder) throws {
		var _container = encoder.container(keyedBy: CodingKeys.self)
		
		// Encode all our properties (own and inherited)
		try activationState.encode(on: &_container, forKey: .activationState)
		try annunciator?.encode(on: &_container, forKey: .annunciator)
		try `extension`?.encode(on: &_container, forKey: .`extension`)
		try id?.encode(on: &_container, forKey: .id, auxiliaryKey: ._id)
		try indication?.encode(on: &_container, forKey: .indication)
		try manifestation?.encode(on: &_container, forKey: .manifestation)
		try modifierExtension?.encode(on: &_container, forKey: .modifierExtension)
		try presence?.encode(on: &_container, forKey: .presence)
		try type?.encode(on: &_container, forKey: .type)
	}
}
